### ISSUE TITLE
missing file ?

### ISSUE THREAD

**Issue by bcharlier** [josephsalmon/HAX712X#7]
Hi @josephsalmon ,

There should be a missing "./scripts/hello-world.py" in Courses/ClassesExceptions/tp.qmd at line https://github.com/josephsalmon/HAX712X/blob/ef8ae6d2fb94b37fc9a1e96fd1ad4522c1adf71a/Courses/ClassesExceptions/tp.qmd#L286

**Comment by josephsalmon** [comment]
file added.
that should solve the pb.
